import type { InterviewState } from '../context/InterviewContext'

// Realistic mock data for demo/QA purposes
// Fictional person: Sarah Mitchell, 42, married, two kids, runs a small design studio

export const mockState: InterviewState = {
  aboutMe: {
    fullName: 'Sarah Mitchell',
    dateOfBirth: 'June 14, 1983',
    location: 'San Francisco, CA',
    reason: 'Just being proactive \u2014 everyone should do this',
    intendedFor: 'My spouse David, my kids Emma and Jack, my sister Lisa',
    personalContext: 'I\'m 42, married to David, and we have two kids (Emma, 8, and Jack, 5). I realized after my friend\'s sudden passing last year that our family had no idea where anything was \u2014 accounts, passwords, insurance policies, none of it. I don\'t want that for mine. This is me getting organized while everything is fine, so nobody has to scramble if it\'s not.',
  },
  contacts: [
    {
      id: crypto.randomUUID(),
      name: 'David Mitchell',
      phone: '(415) 555-0142',
      email: 'david.mitchell@gmail.com',
      relationship: 'Spouse',
      role: 'Spouse / Executor',
      notes: 'Has access to the safe in the home office. Knows the combination.',
    },
    {
      id: crypto.randomUUID(),
      name: 'Karen Chen',
      phone: '(415) 555-0198',
      email: 'karen.chen@lawfirm.com',
      relationship: 'Attorney',
      role: 'Estate Attorney',
      notes: 'Drafted our wills in 2023. Office is on Market Street, Suite 400.',
    },
    {
      id: crypto.randomUUID(),
      name: 'Tom Rivera',
      phone: '(510) 555-0167',
      email: 'trivera@financialadvisors.com',
      relationship: 'Financial advisor',
      role: 'Financial Advisor',
      notes: 'Manages our investment accounts at Schwab. Annual review every January.',
    },
    {
      id: crypto.randomUUID(),
      name: 'Lisa Park',
      phone: '(415) 555-0211',
      email: 'lisa.park@gmail.com',
      relationship: 'Sister',
      role: 'Emergency Contact',
      notes: 'Lives 20 minutes away. Has a spare house key.',
    },
  ],
  financialAccounts: [
    {
      id: crypto.randomUUID(),
      institution: 'Chase Bank',
      accountType: 'Checking',
      approxValue: '$12,000',
      hasBeneficiary: 'No',
      accessNotes: 'Online login is in 1Password. Joint account with David.',
    },
    {
      id: crypto.randomUUID(),
      institution: 'Chase Bank',
      accountType: 'Savings',
      approxValue: '$45,000',
      hasBeneficiary: 'No',
      accessNotes: 'Same login as checking. Emergency fund — 6 months of expenses.',
    },
    {
      id: crypto.randomUUID(),
      institution: 'Charles Schwab',
      accountType: 'Brokerage',
      approxValue: '$320,000',
      hasBeneficiary: 'Yes — David Mitchell',
      accessNotes: 'Tom Rivera (financial advisor) manages this. Login in 1Password.',
    },
    {
      id: crypto.randomUUID(),
      institution: 'Fidelity',
      accountType: '401(k)',
      approxValue: '$185,000',
      hasBeneficiary: 'Yes — David Mitchell',
      accessNotes: 'Through my employer (Studio Mitchell LLC). HR contact: jobs@studiomitchell.com',
    },
    {
      id: crypto.randomUUID(),
      institution: 'Vanguard',
      accountType: 'Roth IRA',
      approxValue: '$67,000',
      hasBeneficiary: 'Yes — David Mitchell',
      accessNotes: 'Login in 1Password. Max contribution each year.',
    },
  ],
  insurancePolicies: [
    {
      id: crypto.randomUUID(),
      carrier: 'Northwestern Mutual',
      insuranceType: 'Term Life',
      policyNumberLocation: 'Policy documents in the fireproof safe, top shelf. Also a PDF in Google Drive under Insurance folder.',
      agentContact: 'Mike Torres, (415) 555-0299, mike.torres@nm.com',
      isEmployerProvided: 'No',
      employerContact: '',
      notes: '$500,000 term policy, 20-year term started 2021. Premiums are auto-drafted from Chase checking.',
    },
    {
      id: crypto.randomUUID(),
      carrier: 'Blue Shield of California',
      insuranceType: 'Health',
      policyNumberLocation: 'Card is in my wallet. Policy details on Blue Shield website — login in 1Password.',
      agentContact: 'Through employer benefits portal',
      isEmployerProvided: 'Yes',
      employerContact: 'Acme Design Co — HR benefits: (415) 555-0300, benefits@acmedesign.co',
      notes: 'Family plan covering David and both kids. Dental and vision are separate through Guardian.',
    },
    {
      id: crypto.randomUUID(),
      carrier: 'State Farm',
      insuranceType: 'Homeowners',
      policyNumberLocation: 'Filing cabinet in home office, "Insurance" folder. Also in Google Drive.',
      agentContact: 'Janet Wu, (415) 555-0188, janet.wu@statefarm.com',
      isEmployerProvided: 'No',
      employerContact: '',
      notes: 'Covers the house and personal property. Earthquake rider is separate. Annual premium ~$2,400.',
    },
  ],
  properties: [
    {
      id: crypto.randomUUID(),
      propertyType: 'Primary Residence',
      description: '3BR/2BA single family home, built 1952, renovated kitchen 2022',
      location: '847 Elm Street, San Francisco, CA 94117',
      deedTitleLocation: 'Original deed in the safe deposit box at Chase (Branch on Divisadero). Copy in Google Drive.',
      hasMortgage: 'Yes — Chase mortgage, ~$380,000 remaining. Monthly payment auto-drafted.',
      notes: 'Jointly owned with David. Estimated value ~$1.2M. Property tax bill comes in October.',
    },
    {
      id: crypto.randomUUID(),
      propertyType: 'Vehicle',
      description: '2021 Volvo XC60, silver, ~35,000 miles',
      location: 'Garage at home',
      deedTitleLocation: 'Title in the filing cabinet under "Auto." Registration in the glove box.',
      hasMortgage: 'No — paid off',
      notes: 'Regular maintenance at Volvo of San Francisco. Service records in Google Drive.',
    },
  ],
  digital: {
    emailAccounts: 'Personal: sarah.mitchell@gmail.com (primary email for everything). Work: sarah@studiomitchell.com (Google Workspace, admin). Old Hotmail: smitchell92@hotmail.com (rarely used but linked to some old accounts).',
    passwordManager: '1Password — the master password is written on a card in the sealed envelope in the fireproof safe (labeled "Digital Access"). David knows about the envelope but not the password. Our family vault has shared logins for streaming, utilities, etc.',
    twoFactorAuth: 'Google Authenticator on my iPhone for most accounts. Backup codes for critical accounts (Google, bank) are saved in a note in 1Password called "2FA Recovery Codes." If my phone is lost, use these codes.',
    socialMediaWishes: 'Instagram (@sarahmdesigns, ~2,400 followers): Memorialize or let Lisa decide — she knows what I\'d want. LinkedIn: Leave active for a few months, then delete. Facebook: Delete — I barely use it. Twitter/X: Delete.',
    cloudStorage: 'Google Drive (personal): Family photos (organized by year), tax documents (2018-present), insurance PDFs, home renovation records. iCloud: iPhone backups, shared family photo library. Dropbox: Old college files and some client work archives — nothing critical.',
    subscriptions: 'Netflix ($15.49/mo), Spotify Family ($16.99/mo), NYT ($4/mo), Adobe Creative Cloud ($54.99/mo — needed for work), Figma ($12/mo — work), iCloud+ ($2.99/mo), YouTube Premium ($13.99/mo). All billed to Chase Visa ending in 4821.',
    crypto: 'No cryptocurrency holdings.',
    domainNames: 'studiomitchell.com — registered at Namecheap, auto-renews yearly ($14/year). Hosting is on Vercel (free tier). sarahmitchelldesign.com — redirect to studiomitchell.com, also at Namecheap.',
    digitalPurchases: 'Kindle library (~200 books, linked to sarah.mitchell@gmail.com). iTunes/Apple purchases under same email. No significant gaming purchases. Southwest Rapid Rewards: ~42,000 points. Marriott Bonvoy: ~18,000 points. Chase Ultimate Rewards: ~85,000 points.',
    loyaltyPrograms: '',
    otherDigital: 'GitHub account (sarahmitchell) has some open-source contributions and client project repos — nothing sensitive. Notion workspace has business operations docs.',
  },
  legalDocuments: [
    {
      id: crypto.randomUUID(),
      documentType: 'Will',
      location: 'Original at Karen Chen\'s office (our attorney). Copy in the fireproof safe and a PDF in Google Drive under "Legal" folder.',
      lastUpdated: 'March 2023',
      notes: 'Leaves everything to David. If David predeceases me, split equally between the kids with Lisa as guardian. Karen has the full details.',
    },
    {
      id: crypto.randomUUID(),
      documentType: 'Living Trust',
      location: 'Same as will — Karen Chen\'s office, safe, and Google Drive.',
      lastUpdated: 'March 2023',
      notes: 'House and investment accounts are in the trust. Mitchell Family Trust. David is co-trustee.',
    },
    {
      id: crypto.randomUUID(),
      documentType: 'Power of Attorney (Financial)',
      location: 'Karen Chen\'s office and a copy in the safe.',
      lastUpdated: 'March 2023',
      notes: 'David is primary agent. Lisa Park is backup.',
    },
    {
      id: crypto.randomUUID(),
      documentType: 'Healthcare Directive / Living Will',
      location: 'Copy with Dr. Patel (primary care physician) and in the safe.',
      lastUpdated: 'March 2023',
      notes: 'David is healthcare proxy. No extraordinary measures if prognosis is terminal. Organ donation — yes.',
    },
  ],
  debts: [
    {
      id: crypto.randomUUID(),
      direction: 'I owe',
      debtType: 'Mortgage',
      lender: 'Chase Home Lending',
      approxBalance: '$380,000',
      isCosigned: 'Joint with David',
      payoffNotes: 'Monthly payment ~$2,800 (includes escrow for taxes and insurance). 30-year fixed at 3.25%, originated 2021. Auto-pay from Chase checking.',
    },
    {
      id: crypto.randomUUID(),
      direction: 'I owe',
      debtType: 'Student Loan',
      lender: 'Federal (Dept. of Education / Nelnet)',
      approxBalance: '$12,000',
      isCosigned: 'No',
      payoffNotes: 'Remaining from grad school. $350/month. Federal loans are discharged upon death — David should NOT pay these off. Just notify Nelnet with a death certificate.',
    },
    {
      id: crypto.randomUUID(),
      direction: 'Owed to me',
      debtType: 'Personal loan',
      lender: 'Brother Mike',
      approxBalance: '$5,000',
      isCosigned: '',
      payoffNotes: 'Lent Mike $5K in 2023 for his car repair. No formal agreement but he knows. David can bring it up with him whenever — no rush, no interest.',
    },
  ],
  business: {
    hasBusiness: 'Yes',
    entityType: 'LLC (Single-member)',
    businessName: 'Studio Mitchell LLC',
    keyContacts: 'Accountant: Rachel Wong, rachel@wongcpa.com, (415) 555-0233. She handles quarterly taxes and annual filing. No employees — I use contractors occasionally.',
    operatingAgreementLocation: 'Filed with California Secretary of State. Copy in Google Drive under "Business/Legal." Karen Chen has a copy too.',
    bankAccountAccess: 'Business checking at Chase (separate from personal). Login in 1Password under "Studio Mitchell." Rachel Wong can also access for tax purposes.',
    successionPlan: 'Wind down gracefully. Notify active clients, complete any work in progress (usually 1-2 projects at a time), and close the LLC. Rachel Wong can handle the tax side. The business has no significant assets beyond the bank balance (~$15,000 operating funds).',
    otherBusinessNotes: 'Client contracts are in Google Drive under "Business/Clients." Most are simple project agreements. No long-term retainers or obligations that would bind my estate.',
  },
  dependents: {
    minorChildren: 'Emma Mitchell, age 8 (born June 2017). Jack Mitchell, age 5 (born September 2020). Both attend Sunset Elementary. Emma has a mild peanut allergy — EpiPen is in her backpack and one at home in the kitchen drawer.',
    guardianshipPreferences: 'Lisa Park (my sister) and her husband Rob. They\'ve agreed to this and it\'s in the will. They live nearby, the kids already spend weekends there regularly, and they share our values about education and parenting. Backup: David\'s parents (George and Marie Mitchell) in Portland.',
    elderlyDependents: 'Mom (Patricia Chen, 71) lives independently in Sacramento. No current care needs but she\'s on our radar. Lisa and I check in weekly. Mom\'s finances are in good shape — she has a pension and Medicare.',
    pets: 'Luna — 4-year-old golden retriever. Vet: Bay Animal Hospital, Dr. Kim, (415) 555-0177. She\'s on heartworm medication (monthly). Food: Blue Buffalo, ordered from Chewy (auto-ship). Lisa has agreed to take Luna if needed.',
    specialNeeds: '',
    otherCareNotes: 'Emma is in soccer (Saturday mornings, Golden Gate Park) and piano (Tuesday after school with Mrs. Chen — not related to our attorney). Jack starts T-ball in spring. Their school emergency contacts are David, me, and Lisa, in that order.',
  },
  wishes: {
    healthcareWishes: 'DNR — do not resuscitate if there\'s no reasonable chance of meaningful recovery. No long-term life support or feeding tubes. Dr. Patel (primary care, 415-555-0142) knows my wishes and has a copy of my advance directive. David is my healthcare proxy and knows I feel strongly about this. If the doctors say there\'s no coming back, let me go.',
    funeralPreferences: 'Cremation. No formal funeral — I\'d rather have a celebration of life at home or at Crissy Field (our favorite family spot). Keep it informal, outdoors if weather allows. Play the "Songs I Love" playlist from my Spotify. Wildflowers instead of formal arrangements. If people want to do something, ask them to donate to SF-Marin Food Bank instead of sending flowers.',
    organDonation: 'Yes — registered organ donor (it\'s on my driver\'s license). I\'m comfortable donating any organs or tissue that can help someone.',
    personalMessages: 'David: You\'ve been my person since we were 23. Thank you for building this life with me. The kids are lucky to have you. Don\'t rush through grief, but don\'t stay stuck in it either. You\'re going to be an amazing single parent — you already are an amazing dad.\n\nEmma and Jack: I am so proud of who you are. Be kind, be curious, take care of each other. I hope you know how much I loved being your mom. Every single day.\n\nLisa: Thank you for always being there. I trust you with the kids more than anyone. You know what I would have wanted for them — raise them to be brave and compassionate.\n\nMom: You showed me what strength looks like. I\'m sorry for the pain this causes you. Lean on Lisa and David. They\'ll take care of you.',
    valuesStatement: 'I believe in leaving things better than you found them. I tried to live that way — in my work, in our community, in how we raise the kids. I value honesty over comfort, kindness over being right, and experiences over things. I hope our family keeps the Friday pizza night tradition, keeps exploring new places together, and keeps the house full of music and laughter.',
    otherWishes: 'I\'d love for the kids to have access to my photo library when they\'re older — there are thousands of photos organized by year in Google Drive and iCloud. The "Family" folder has the best ones.\n\nIf the house feels too big for David alone, it\'s okay to sell it. No guilt. The neighborhood is great but the house is just walls — the family is what made it home.',
  },
  verification: {
    fullName: 'Sarah Mitchell',
    verificationDate: 'February 21, 2026',
    familyPassphrase: 'When Emma was born, the first song I sang to her was "Blackbird" by The Beatles. David was crying so hard he couldn\'t sing along. And the nurse said "well, at least one of you can carry a tune."',
    signatureData: '',
  },
  lastSaved: null,
  currentSection: 'contacts',
}
